/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for AddProduct type.
 */
public class AddProduct {
    private String productRatePlanId;
    private List<UpdateOrAddProductChargeOverride> updateOrAddProductChargeOverrides;

    /**
     * Default constructor.
     */
    public AddProduct() {
    }

    /**
     * Initialization constructor.
     * @param  productRatePlanId  String value for productRatePlanId.
     * @param  updateOrAddProductChargeOverrides  List of UpdateOrAddProductChargeOverride value for
     *         updateOrAddProductChargeOverrides.
     */
    public AddProduct(
            String productRatePlanId,
            List<UpdateOrAddProductChargeOverride> updateOrAddProductChargeOverrides) {
        this.productRatePlanId = productRatePlanId;
        this.updateOrAddProductChargeOverrides = updateOrAddProductChargeOverrides;
    }

    /**
     * Getter for ProductRatePlanId.
     * Internal identifier of the product rate plan that the rate plan is based on.
     * @return Returns the String
     */
    @JsonGetter("productRatePlanId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProductRatePlanId() {
        return productRatePlanId;
    }

    /**
     * Setter for ProductRatePlanId.
     * Internal identifier of the product rate plan that the rate plan is based on.
     * @param productRatePlanId Value for String
     */
    @JsonSetter("productRatePlanId")
    public void setProductRatePlanId(String productRatePlanId) {
        this.productRatePlanId = productRatePlanId;
    }

    /**
     * Getter for UpdateOrAddProductChargeOverrides.
     * @return Returns the List of UpdateOrAddProductChargeOverride
     */
    @JsonGetter("updateOrAddProductChargeOverrides")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<UpdateOrAddProductChargeOverride> getUpdateOrAddProductChargeOverrides() {
        return updateOrAddProductChargeOverrides;
    }

    /**
     * Setter for UpdateOrAddProductChargeOverrides.
     * @param updateOrAddProductChargeOverrides Value for List of UpdateOrAddProductChargeOverride
     */
    @JsonSetter("updateOrAddProductChargeOverrides")
    public void setUpdateOrAddProductChargeOverrides(List<UpdateOrAddProductChargeOverride> updateOrAddProductChargeOverrides) {
        this.updateOrAddProductChargeOverrides = updateOrAddProductChargeOverrides;
    }

    /**
     * Converts this AddProduct into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AddProduct [" + "productRatePlanId=" + productRatePlanId
                + ", updateOrAddProductChargeOverrides=" + updateOrAddProductChargeOverrides + "]";
    }

    /**
     * Builds a new {@link AddProduct.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AddProduct.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .productRatePlanId(getProductRatePlanId())
                .updateOrAddProductChargeOverrides(getUpdateOrAddProductChargeOverrides());
        return builder;
    }

    /**
     * Class to build instances of {@link AddProduct}.
     */
    public static class Builder {
        private String productRatePlanId;
        private List<UpdateOrAddProductChargeOverride> updateOrAddProductChargeOverrides;



        /**
         * Setter for productRatePlanId.
         * @param  productRatePlanId  String value for productRatePlanId.
         * @return Builder
         */
        public Builder productRatePlanId(String productRatePlanId) {
            this.productRatePlanId = productRatePlanId;
            return this;
        }

        /**
         * Setter for updateOrAddProductChargeOverrides.
         * @param  updateOrAddProductChargeOverrides  List of UpdateOrAddProductChargeOverride value
         *         for updateOrAddProductChargeOverrides.
         * @return Builder
         */
        public Builder updateOrAddProductChargeOverrides(
                List<UpdateOrAddProductChargeOverride> updateOrAddProductChargeOverrides) {
            this.updateOrAddProductChargeOverrides = updateOrAddProductChargeOverrides;
            return this;
        }

        /**
         * Builds a new {@link AddProduct} object using the set fields.
         * @return {@link AddProduct}
         */
        public AddProduct build() {
            return new AddProduct(productRatePlanId, updateOrAddProductChargeOverrides);
        }
    }
}
