/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CancelReqType type.
 */
public class CancelReqType {
    private String subscriptionId;
    private SubscriptionSourceEnum subscriptionSource;
    private String cancelReason;
    private String cancelDate;

    /**
     * Default constructor.
     */
    public CancelReqType() {
    }

    /**
     * Initialization constructor.
     * @param  subscriptionId  String value for subscriptionId.
     * @param  subscriptionSource  SubscriptionSourceEnum value for subscriptionSource.
     * @param  cancelReason  String value for cancelReason.
     * @param  cancelDate  String value for cancelDate.
     */
    public CancelReqType(
            String subscriptionId,
            SubscriptionSourceEnum subscriptionSource,
            String cancelReason,
            String cancelDate) {
        this.subscriptionId = subscriptionId;
        this.subscriptionSource = subscriptionSource;
        this.cancelReason = cancelReason;
        this.cancelDate = cancelDate;
    }

    /**
     * Getter for SubscriptionId.
     * Subscription id
     * @return Returns the String
     */
    @JsonGetter("subscriptionId")
    public String getSubscriptionId() {
        return subscriptionId;
    }

    /**
     * Setter for SubscriptionId.
     * Subscription id
     * @param subscriptionId Value for String
     */
    @JsonSetter("subscriptionId")
    public void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    /**
     * Getter for SubscriptionSource.
     * Internal or external
     * @return Returns the SubscriptionSourceEnum
     */
    @JsonGetter("subscriptionSource")
    public SubscriptionSourceEnum getSubscriptionSource() {
        return subscriptionSource;
    }

    /**
     * Setter for SubscriptionSource.
     * Internal or external
     * @param subscriptionSource Value for SubscriptionSourceEnum
     */
    @JsonSetter("subscriptionSource")
    public void setSubscriptionSource(SubscriptionSourceEnum subscriptionSource) {
        this.subscriptionSource = subscriptionSource;
    }

    /**
     * Getter for CancelReason.
     * Reason for subscription cancel
     * @return Returns the String
     */
    @JsonGetter("cancelReason")
    public String getCancelReason() {
        return cancelReason;
    }

    /**
     * Setter for CancelReason.
     * Reason for subscription cancel
     * @param cancelReason Value for String
     */
    @JsonSetter("cancelReason")
    public void setCancelReason(String cancelReason) {
        this.cancelReason = cancelReason;
    }

    /**
     * Getter for CancelDate.
     * cancellation date
     * @return Returns the String
     */
    @JsonGetter("cancelDate")
    public String getCancelDate() {
        return cancelDate;
    }

    /**
     * Setter for CancelDate.
     * cancellation date
     * @param cancelDate Value for String
     */
    @JsonSetter("cancelDate")
    public void setCancelDate(String cancelDate) {
        this.cancelDate = cancelDate;
    }

    /**
     * Converts this CancelReqType into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CancelReqType [" + "subscriptionId=" + subscriptionId + ", subscriptionSource="
                + subscriptionSource + ", cancelReason=" + cancelReason + ", cancelDate="
                + cancelDate + "]";
    }

    /**
     * Builds a new {@link CancelReqType.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CancelReqType.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(subscriptionId, subscriptionSource, cancelReason, cancelDate);
        return builder;
    }

    /**
     * Class to build instances of {@link CancelReqType}.
     */
    public static class Builder {
        private String subscriptionId;
        private SubscriptionSourceEnum subscriptionSource;
        private String cancelReason;
        private String cancelDate;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  subscriptionId  String value for subscriptionId.
         * @param  subscriptionSource  SubscriptionSourceEnum value for subscriptionSource.
         * @param  cancelReason  String value for cancelReason.
         * @param  cancelDate  String value for cancelDate.
         */
        public Builder(String subscriptionId, SubscriptionSourceEnum subscriptionSource,
                String cancelReason, String cancelDate) {
            this.subscriptionId = subscriptionId;
            this.subscriptionSource = subscriptionSource;
            this.cancelReason = cancelReason;
            this.cancelDate = cancelDate;
        }

        /**
         * Setter for subscriptionId.
         * @param  subscriptionId  String value for subscriptionId.
         * @return Builder
         */
        public Builder subscriptionId(String subscriptionId) {
            this.subscriptionId = subscriptionId;
            return this;
        }

        /**
         * Setter for subscriptionSource.
         * @param  subscriptionSource  SubscriptionSourceEnum value for subscriptionSource.
         * @return Builder
         */
        public Builder subscriptionSource(SubscriptionSourceEnum subscriptionSource) {
            this.subscriptionSource = subscriptionSource;
            return this;
        }

        /**
         * Setter for cancelReason.
         * @param  cancelReason  String value for cancelReason.
         * @return Builder
         */
        public Builder cancelReason(String cancelReason) {
            this.cancelReason = cancelReason;
            return this;
        }

        /**
         * Setter for cancelDate.
         * @param  cancelDate  String value for cancelDate.
         * @return Builder
         */
        public Builder cancelDate(String cancelDate) {
            this.cancelDate = cancelDate;
            return this;
        }

        /**
         * Builds a new {@link CancelReqType} object using the set fields.
         * @return {@link CancelReqType}
         */
        public CancelReqType build() {
            return new CancelReqType(subscriptionId, subscriptionSource, cancelReason, cancelDate);
        }
    }
}
