/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for CreateSubscription type.
 */
public class CreateSubscription {
    private Terms terms;
    private List<SubscribeToRatePlan> subscribeToRatePlans;

    /**
     * Default constructor.
     */
    public CreateSubscription() {
    }

    /**
     * Initialization constructor.
     * @param  terms  Terms value for terms.
     * @param  subscribeToRatePlans  List of SubscribeToRatePlan value for subscribeToRatePlans.
     */
    public CreateSubscription(
            Terms terms,
            List<SubscribeToRatePlan> subscribeToRatePlans) {
        this.terms = terms;
        this.subscribeToRatePlans = subscribeToRatePlans;
    }

    /**
     * Getter for Terms.
     * Container for the terms and renewal settings of the subscription.
     * @return Returns the Terms
     */
    @JsonGetter("terms")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Terms getTerms() {
        return terms;
    }

    /**
     * Setter for Terms.
     * Container for the terms and renewal settings of the subscription.
     * @param terms Value for Terms
     */
    @JsonSetter("terms")
    public void setTerms(Terms terms) {
        this.terms = terms;
    }

    /**
     * Getter for SubscribeToRatePlans.
     * @return Returns the List of SubscribeToRatePlan
     */
    @JsonGetter("subscribeToRatePlans")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<SubscribeToRatePlan> getSubscribeToRatePlans() {
        return subscribeToRatePlans;
    }

    /**
     * Setter for SubscribeToRatePlans.
     * @param subscribeToRatePlans Value for List of SubscribeToRatePlan
     */
    @JsonSetter("subscribeToRatePlans")
    public void setSubscribeToRatePlans(List<SubscribeToRatePlan> subscribeToRatePlans) {
        this.subscribeToRatePlans = subscribeToRatePlans;
    }

    /**
     * Converts this CreateSubscription into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateSubscription [" + "terms=" + terms + ", subscribeToRatePlans="
                + subscribeToRatePlans + "]";
    }

    /**
     * Builds a new {@link CreateSubscription.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateSubscription.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .terms(getTerms())
                .subscribeToRatePlans(getSubscribeToRatePlans());
        return builder;
    }

    /**
     * Class to build instances of {@link CreateSubscription}.
     */
    public static class Builder {
        private Terms terms;
        private List<SubscribeToRatePlan> subscribeToRatePlans;



        /**
         * Setter for terms.
         * @param  terms  Terms value for terms.
         * @return Builder
         */
        public Builder terms(Terms terms) {
            this.terms = terms;
            return this;
        }

        /**
         * Setter for subscribeToRatePlans.
         * @param  subscribeToRatePlans  List of SubscribeToRatePlan value for subscribeToRatePlans.
         * @return Builder
         */
        public Builder subscribeToRatePlans(List<SubscribeToRatePlan> subscribeToRatePlans) {
            this.subscribeToRatePlans = subscribeToRatePlans;
            return this;
        }

        /**
         * Builds a new {@link CreateSubscription} object using the set fields.
         * @return {@link CreateSubscription}
         */
        public CreateSubscription build() {
            return new CreateSubscription(terms, subscribeToRatePlans);
        }
    }
}
