/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CustomerFacingCustomFields type.
 */
public class CustomerFacingCustomFields {
    private String customerFacingC;

    /**
     * Default constructor.
     */
    public CustomerFacingCustomFields() {
    }

    /**
     * Initialization constructor.
     * @param  customerFacingC  String value for customerFacingC.
     */
    public CustomerFacingCustomFields(
            String customerFacingC) {
        this.customerFacingC = customerFacingC;
    }

    /**
     * Getter for CustomerFacingC.
     * @return Returns the String
     */
    @JsonGetter("customerFacing__c")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCustomerFacingC() {
        return customerFacingC;
    }

    /**
     * Setter for CustomerFacingC.
     * @param customerFacingC Value for String
     */
    @JsonSetter("customerFacing__c")
    public void setCustomerFacingC(String customerFacingC) {
        this.customerFacingC = customerFacingC;
    }

    /**
     * Converts this CustomerFacingCustomFields into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CustomerFacingCustomFields [" + "customerFacingC=" + customerFacingC + "]";
    }

    /**
     * Builds a new {@link CustomerFacingCustomFields.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CustomerFacingCustomFields.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .customerFacingC(getCustomerFacingC());
        return builder;
    }

    /**
     * Class to build instances of {@link CustomerFacingCustomFields}.
     */
    public static class Builder {
        private String customerFacingC;



        /**
         * Setter for customerFacingC.
         * @param  customerFacingC  String value for customerFacingC.
         * @return Builder
         */
        public Builder customerFacingC(String customerFacingC) {
            this.customerFacingC = customerFacingC;
            return this;
        }

        /**
         * Builds a new {@link CustomerFacingCustomFields} object using the set fields.
         * @return {@link CustomerFacingCustomFields}
         */
        public CustomerFacingCustomFields build() {
            return new CustomerFacingCustomFields(customerFacingC);
        }
    }
}
