/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * EndDateConditionEnum to be used.
 */
public enum EndDateConditionEnum {
    SUBSCRIPTION_END,

    FIXED_PERIOD,

    SPECIFIC_END_DATE;


    private static TreeMap<String, EndDateConditionEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        SUBSCRIPTION_END.value = "Subscription_End";
        FIXED_PERIOD.value = "Fixed_Period";
        SPECIFIC_END_DATE.value = "Specific_End_Date";

        valueMap.put("Subscription_End", SUBSCRIPTION_END);
        valueMap.put("Fixed_Period", FIXED_PERIOD);
        valueMap.put("Specific_End_Date", SPECIFIC_END_DATE);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static EndDateConditionEnum constructFromString(String toConvert) throws IOException {
        EndDateConditionEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static EndDateConditionEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of EndDateConditionEnum values to list of string values.
     * @param toConvert The list of EndDateConditionEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<EndDateConditionEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (EndDateConditionEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 