/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for OrderRequestTypeSubscription type.
 */
public class OrderRequestTypeSubscription {
    private List<CreateOrderOrderAction> orderActions;

    /**
     * Default constructor.
     */
    public OrderRequestTypeSubscription() {
    }

    /**
     * Initialization constructor.
     * @param  orderActions  List of CreateOrderOrderAction value for orderActions.
     */
    public OrderRequestTypeSubscription(
            List<CreateOrderOrderAction> orderActions) {
        this.orderActions = orderActions;
    }

    /**
     * Getter for OrderActions.
     * The actions to be applied to the subscription. Order actions will be stored with the sequence
     * when it was provided in the request.
     * @return Returns the List of CreateOrderOrderAction
     */
    @JsonGetter("orderActions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<CreateOrderOrderAction> getOrderActions() {
        return orderActions;
    }

    /**
     * Setter for OrderActions.
     * The actions to be applied to the subscription. Order actions will be stored with the sequence
     * when it was provided in the request.
     * @param orderActions Value for List of CreateOrderOrderAction
     */
    @JsonSetter("orderActions")
    public void setOrderActions(List<CreateOrderOrderAction> orderActions) {
        this.orderActions = orderActions;
    }

    /**
     * Converts this OrderRequestTypeSubscription into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrderRequestTypeSubscription [" + "orderActions=" + orderActions + "]";
    }

    /**
     * Builds a new {@link OrderRequestTypeSubscription.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OrderRequestTypeSubscription.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .orderActions(getOrderActions());
        return builder;
    }

    /**
     * Class to build instances of {@link OrderRequestTypeSubscription}.
     */
    public static class Builder {
        private List<CreateOrderOrderAction> orderActions;



        /**
         * Setter for orderActions.
         * @param  orderActions  List of CreateOrderOrderAction value for orderActions.
         * @return Builder
         */
        public Builder orderActions(List<CreateOrderOrderAction> orderActions) {
            this.orderActions = orderActions;
            return this;
        }

        /**
         * Builds a new {@link OrderRequestTypeSubscription} object using the set fields.
         * @return {@link OrderRequestTypeSubscription}
         */
        public OrderRequestTypeSubscription build() {
            return new OrderRequestTypeSubscription(orderActions);
        }
    }
}
