/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for OverridesPricing type.
 */
public class OverridesPricing {
    private Discount discount;

    /**
     * Default constructor.
     */
    public OverridesPricing() {
    }

    /**
     * Initialization constructor.
     * @param  discount  Discount value for discount.
     */
    public OverridesPricing(
            Discount discount) {
        this.discount = discount;
    }

    /**
     * Getter for Discount.
     * @return Returns the Discount
     */
    @JsonGetter("discount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Discount getDiscount() {
        return discount;
    }

    /**
     * Setter for Discount.
     * @param discount Value for Discount
     */
    @JsonSetter("discount")
    public void setDiscount(Discount discount) {
        this.discount = discount;
    }

    /**
     * Converts this OverridesPricing into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OverridesPricing [" + "discount=" + discount + "]";
    }

    /**
     * Builds a new {@link OverridesPricing.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OverridesPricing.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .discount(getDiscount());
        return builder;
    }

    /**
     * Class to build instances of {@link OverridesPricing}.
     */
    public static class Builder {
        private Discount discount;



        /**
         * Setter for discount.
         * @param  discount  Discount value for discount.
         * @return Builder
         */
        public Builder discount(Discount discount) {
            this.discount = discount;
            return this;
        }

        /**
         * Builds a new {@link OverridesPricing} object using the set fields.
         * @return {@link OverridesPricing}
         */
        public OverridesPricing build() {
            return new OverridesPricing(discount);
        }
    }
}
