/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RatePlanPricing type.
 */
public class RatePlanPricing {
    private Discount discount;
    private RecurringFlatFee recurringFlatFee;

    /**
     * Default constructor.
     */
    public RatePlanPricing() {
    }

    /**
     * Initialization constructor.
     * @param  discount  Discount value for discount.
     * @param  recurringFlatFee  RecurringFlatFee value for recurringFlatFee.
     */
    public RatePlanPricing(
            Discount discount,
            RecurringFlatFee recurringFlatFee) {
        this.discount = discount;
        this.recurringFlatFee = recurringFlatFee;
    }

    /**
     * Getter for Discount.
     * @return Returns the Discount
     */
    @JsonGetter("discount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Discount getDiscount() {
        return discount;
    }

    /**
     * Setter for Discount.
     * @param discount Value for Discount
     */
    @JsonSetter("discount")
    public void setDiscount(Discount discount) {
        this.discount = discount;
    }

    /**
     * Getter for RecurringFlatFee.
     * @return Returns the RecurringFlatFee
     */
    @JsonGetter("recurringFlatFee")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RecurringFlatFee getRecurringFlatFee() {
        return recurringFlatFee;
    }

    /**
     * Setter for RecurringFlatFee.
     * @param recurringFlatFee Value for RecurringFlatFee
     */
    @JsonSetter("recurringFlatFee")
    public void setRecurringFlatFee(RecurringFlatFee recurringFlatFee) {
        this.recurringFlatFee = recurringFlatFee;
    }

    /**
     * Converts this RatePlanPricing into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RatePlanPricing [" + "discount=" + discount + ", recurringFlatFee="
                + recurringFlatFee + "]";
    }

    /**
     * Builds a new {@link RatePlanPricing.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RatePlanPricing.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .discount(getDiscount())
                .recurringFlatFee(getRecurringFlatFee());
        return builder;
    }

    /**
     * Class to build instances of {@link RatePlanPricing}.
     */
    public static class Builder {
        private Discount discount;
        private RecurringFlatFee recurringFlatFee;



        /**
         * Setter for discount.
         * @param  discount  Discount value for discount.
         * @return Builder
         */
        public Builder discount(Discount discount) {
            this.discount = discount;
            return this;
        }

        /**
         * Setter for recurringFlatFee.
         * @param  recurringFlatFee  RecurringFlatFee value for recurringFlatFee.
         * @return Builder
         */
        public Builder recurringFlatFee(RecurringFlatFee recurringFlatFee) {
            this.recurringFlatFee = recurringFlatFee;
            return this;
        }

        /**
         * Builds a new {@link RatePlanPricing} object using the set fields.
         * @return {@link RatePlanPricing}
         */
        public RatePlanPricing build() {
            return new RatePlanPricing(discount, recurringFlatFee);
        }
    }
}
