/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RemoveProduct type.
 */
public class RemoveProduct {
    private String productRatePlanId;

    /**
     * Default constructor.
     */
    public RemoveProduct() {
    }

    /**
     * Initialization constructor.
     * @param  productRatePlanId  String value for productRatePlanId.
     */
    public RemoveProduct(
            String productRatePlanId) {
        this.productRatePlanId = productRatePlanId;
    }

    /**
     * Getter for ProductRatePlanId.
     * Internal identifier of the product rate plan that the rate plan is based on.
     * @return Returns the String
     */
    @JsonGetter("productRatePlanId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProductRatePlanId() {
        return productRatePlanId;
    }

    /**
     * Setter for ProductRatePlanId.
     * Internal identifier of the product rate plan that the rate plan is based on.
     * @param productRatePlanId Value for String
     */
    @JsonSetter("productRatePlanId")
    public void setProductRatePlanId(String productRatePlanId) {
        this.productRatePlanId = productRatePlanId;
    }

    /**
     * Converts this RemoveProduct into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RemoveProduct [" + "productRatePlanId=" + productRatePlanId + "]";
    }

    /**
     * Builds a new {@link RemoveProduct.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RemoveProduct.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .productRatePlanId(getProductRatePlanId());
        return builder;
    }

    /**
     * Class to build instances of {@link RemoveProduct}.
     */
    public static class Builder {
        private String productRatePlanId;



        /**
         * Setter for productRatePlanId.
         * @param  productRatePlanId  String value for productRatePlanId.
         * @return Builder
         */
        public Builder productRatePlanId(String productRatePlanId) {
            this.productRatePlanId = productRatePlanId;
            return this;
        }

        /**
         * Builds a new {@link RemoveProduct} object using the set fields.
         * @return {@link RemoveProduct}
         */
        public RemoveProduct build() {
            return new RemoveProduct(productRatePlanId);
        }
    }
}
