/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RenewalTerm type.
 */
public class RenewalTerm {
    private Integer period;
    private PeriodTypeEnum periodType;

    /**
     * Default constructor.
     */
    public RenewalTerm() {
    }

    /**
     * Initialization constructor.
     * @param  period  Integer value for period.
     * @param  periodType  PeriodTypeEnum value for periodType.
     */
    public RenewalTerm(
            Integer period,
            PeriodTypeEnum periodType) {
        this.period = period;
        this.periodType = periodType;
    }

    /**
     * Getter for Period.
     * Duration of the renewal term in months, years, days, or weeks, depending on the value of the
     * `periodType` field.
     * @return Returns the Integer
     */
    @JsonGetter("period")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPeriod() {
        return period;
    }

    /**
     * Setter for Period.
     * Duration of the renewal term in months, years, days, or weeks, depending on the value of the
     * `periodType` field.
     * @param period Value for Integer
     */
    @JsonSetter("period")
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * Getter for PeriodType.
     * Unit of time that the renewal term is measured in.
     * @return Returns the PeriodTypeEnum
     */
    @JsonGetter("periodType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PeriodTypeEnum getPeriodType() {
        return periodType;
    }

    /**
     * Setter for PeriodType.
     * Unit of time that the renewal term is measured in.
     * @param periodType Value for PeriodTypeEnum
     */
    @JsonSetter("periodType")
    public void setPeriodType(PeriodTypeEnum periodType) {
        this.periodType = periodType;
    }

    /**
     * Converts this RenewalTerm into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RenewalTerm [" + "period=" + period + ", periodType=" + periodType + "]";
    }

    /**
     * Builds a new {@link RenewalTerm.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RenewalTerm.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .period(getPeriod())
                .periodType(getPeriodType());
        return builder;
    }

    /**
     * Class to build instances of {@link RenewalTerm}.
     */
    public static class Builder {
        private Integer period;
        private PeriodTypeEnum periodType;



        /**
         * Setter for period.
         * @param  period  Integer value for period.
         * @return Builder
         */
        public Builder period(Integer period) {
            this.period = period;
            return this;
        }

        /**
         * Setter for periodType.
         * @param  periodType  PeriodTypeEnum value for periodType.
         * @return Builder
         */
        public Builder periodType(PeriodTypeEnum periodType) {
            this.periodType = periodType;
            return this;
        }

        /**
         * Builds a new {@link RenewalTerm} object using the set fields.
         * @return {@link RenewalTerm}
         */
        public RenewalTerm build() {
            return new RenewalTerm(period, periodType);
        }
    }
}
