/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SubscribeToRatePlansChargeOverride type.
 */
public class SubscribeToRatePlansChargeOverride {
    private String productRatePlanChargeId;
    private CustomerFacingCustomFields customerFacingCustomFields;
    private RatePlanPricing ratePlanPricing;
    private RatePlanEndDate ratePlanEndDate;

    /**
     * Default constructor.
     */
    public SubscribeToRatePlansChargeOverride() {
    }

    /**
     * Initialization constructor.
     * @param  productRatePlanChargeId  String value for productRatePlanChargeId.
     * @param  customerFacingCustomFields  CustomerFacingCustomFields value for
     *         customerFacingCustomFields.
     * @param  ratePlanPricing  RatePlanPricing value for ratePlanPricing.
     * @param  ratePlanEndDate  RatePlanEndDate value for ratePlanEndDate.
     */
    public SubscribeToRatePlansChargeOverride(
            String productRatePlanChargeId,
            CustomerFacingCustomFields customerFacingCustomFields,
            RatePlanPricing ratePlanPricing,
            RatePlanEndDate ratePlanEndDate) {
        this.productRatePlanChargeId = productRatePlanChargeId;
        this.customerFacingCustomFields = customerFacingCustomFields;
        this.ratePlanPricing = ratePlanPricing;
        this.ratePlanEndDate = ratePlanEndDate;
    }

    /**
     * Getter for ProductRatePlanChargeId.
     * This is unique rate plan charge id respective to rate plan id. It signifies the subscription
     * type,entitlementLevel,maxEntitlements,numEntitlements etc.
     * @return Returns the String
     */
    @JsonGetter("productRatePlanChargeId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProductRatePlanChargeId() {
        return productRatePlanChargeId;
    }

    /**
     * Setter for ProductRatePlanChargeId.
     * This is unique rate plan charge id respective to rate plan id. It signifies the subscription
     * type,entitlementLevel,maxEntitlements,numEntitlements etc.
     * @param productRatePlanChargeId Value for String
     */
    @JsonSetter("productRatePlanChargeId")
    public void setProductRatePlanChargeId(String productRatePlanChargeId) {
        this.productRatePlanChargeId = productRatePlanChargeId;
    }

    /**
     * Getter for CustomerFacingCustomFields.
     * @return Returns the CustomerFacingCustomFields
     */
    @JsonGetter("customerFacingCustomFields")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CustomerFacingCustomFields getCustomerFacingCustomFields() {
        return customerFacingCustomFields;
    }

    /**
     * Setter for CustomerFacingCustomFields.
     * @param customerFacingCustomFields Value for CustomerFacingCustomFields
     */
    @JsonSetter("customerFacingCustomFields")
    public void setCustomerFacingCustomFields(CustomerFacingCustomFields customerFacingCustomFields) {
        this.customerFacingCustomFields = customerFacingCustomFields;
    }

    /**
     * Getter for RatePlanPricing.
     * @return Returns the RatePlanPricing
     */
    @JsonGetter("ratePlanPricing")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RatePlanPricing getRatePlanPricing() {
        return ratePlanPricing;
    }

    /**
     * Setter for RatePlanPricing.
     * @param ratePlanPricing Value for RatePlanPricing
     */
    @JsonSetter("ratePlanPricing")
    public void setRatePlanPricing(RatePlanPricing ratePlanPricing) {
        this.ratePlanPricing = ratePlanPricing;
    }

    /**
     * Getter for RatePlanEndDate.
     * @return Returns the RatePlanEndDate
     */
    @JsonGetter("ratePlanEndDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RatePlanEndDate getRatePlanEndDate() {
        return ratePlanEndDate;
    }

    /**
     * Setter for RatePlanEndDate.
     * @param ratePlanEndDate Value for RatePlanEndDate
     */
    @JsonSetter("ratePlanEndDate")
    public void setRatePlanEndDate(RatePlanEndDate ratePlanEndDate) {
        this.ratePlanEndDate = ratePlanEndDate;
    }

    /**
     * Converts this SubscribeToRatePlansChargeOverride into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SubscribeToRatePlansChargeOverride [" + "productRatePlanChargeId="
                + productRatePlanChargeId + ", customerFacingCustomFields="
                + customerFacingCustomFields + ", ratePlanPricing=" + ratePlanPricing
                + ", ratePlanEndDate=" + ratePlanEndDate + "]";
    }

    /**
     * Builds a new {@link SubscribeToRatePlansChargeOverride.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SubscribeToRatePlansChargeOverride.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .productRatePlanChargeId(getProductRatePlanChargeId())
                .customerFacingCustomFields(getCustomerFacingCustomFields())
                .ratePlanPricing(getRatePlanPricing())
                .ratePlanEndDate(getRatePlanEndDate());
        return builder;
    }

    /**
     * Class to build instances of {@link SubscribeToRatePlansChargeOverride}.
     */
    public static class Builder {
        private String productRatePlanChargeId;
        private CustomerFacingCustomFields customerFacingCustomFields;
        private RatePlanPricing ratePlanPricing;
        private RatePlanEndDate ratePlanEndDate;



        /**
         * Setter for productRatePlanChargeId.
         * @param  productRatePlanChargeId  String value for productRatePlanChargeId.
         * @return Builder
         */
        public Builder productRatePlanChargeId(String productRatePlanChargeId) {
            this.productRatePlanChargeId = productRatePlanChargeId;
            return this;
        }

        /**
         * Setter for customerFacingCustomFields.
         * @param  customerFacingCustomFields  CustomerFacingCustomFields value for
         *         customerFacingCustomFields.
         * @return Builder
         */
        public Builder customerFacingCustomFields(
                CustomerFacingCustomFields customerFacingCustomFields) {
            this.customerFacingCustomFields = customerFacingCustomFields;
            return this;
        }

        /**
         * Setter for ratePlanPricing.
         * @param  ratePlanPricing  RatePlanPricing value for ratePlanPricing.
         * @return Builder
         */
        public Builder ratePlanPricing(RatePlanPricing ratePlanPricing) {
            this.ratePlanPricing = ratePlanPricing;
            return this;
        }

        /**
         * Setter for ratePlanEndDate.
         * @param  ratePlanEndDate  RatePlanEndDate value for ratePlanEndDate.
         * @return Builder
         */
        public Builder ratePlanEndDate(RatePlanEndDate ratePlanEndDate) {
            this.ratePlanEndDate = ratePlanEndDate;
            return this;
        }

        /**
         * Builds a new {@link SubscribeToRatePlansChargeOverride} object using the set fields.
         * @return {@link SubscribeToRatePlansChargeOverride}
         */
        public SubscribeToRatePlansChargeOverride build() {
            return new SubscribeToRatePlansChargeOverride(productRatePlanChargeId,
                    customerFacingCustomFields, ratePlanPricing, ratePlanEndDate);
        }
    }
}
