/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SubscribeToRatePlan type.
 */
public class SubscribeToRatePlan {
    private String productRatePlanId;
    private List<SubscribeToRatePlansChargeOverride> subscribeToRatePlansChargeOverrides;

    /**
     * Default constructor.
     */
    public SubscribeToRatePlan() {
    }

    /**
     * Initialization constructor.
     * @param  productRatePlanId  String value for productRatePlanId.
     * @param  subscribeToRatePlansChargeOverrides  List of SubscribeToRatePlansChargeOverride value
     *         for subscribeToRatePlansChargeOverrides.
     */
    public SubscribeToRatePlan(
            String productRatePlanId,
            List<SubscribeToRatePlansChargeOverride> subscribeToRatePlansChargeOverrides) {
        this.productRatePlanId = productRatePlanId;
        this.subscribeToRatePlansChargeOverrides = subscribeToRatePlansChargeOverrides;
    }

    /**
     * Getter for ProductRatePlanId.
     * This is unique Product Rate Plan id which signifies the subscription
     * type,entitlementLevel,maxEntitlements,numEntitlements etc.
     * @return Returns the String
     */
    @JsonGetter("productRatePlanId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProductRatePlanId() {
        return productRatePlanId;
    }

    /**
     * Setter for ProductRatePlanId.
     * This is unique Product Rate Plan id which signifies the subscription
     * type,entitlementLevel,maxEntitlements,numEntitlements etc.
     * @param productRatePlanId Value for String
     */
    @JsonSetter("productRatePlanId")
    public void setProductRatePlanId(String productRatePlanId) {
        this.productRatePlanId = productRatePlanId;
    }

    /**
     * Getter for SubscribeToRatePlansChargeOverrides.
     * @return Returns the List of SubscribeToRatePlansChargeOverride
     */
    @JsonGetter("subscribeToRatePlansChargeOverrides")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<SubscribeToRatePlansChargeOverride> getSubscribeToRatePlansChargeOverrides() {
        return subscribeToRatePlansChargeOverrides;
    }

    /**
     * Setter for SubscribeToRatePlansChargeOverrides.
     * @param subscribeToRatePlansChargeOverrides Value for List of SubscribeToRatePlansChargeOverride
     */
    @JsonSetter("subscribeToRatePlansChargeOverrides")
    public void setSubscribeToRatePlansChargeOverrides(List<SubscribeToRatePlansChargeOverride> subscribeToRatePlansChargeOverrides) {
        this.subscribeToRatePlansChargeOverrides = subscribeToRatePlansChargeOverrides;
    }

    /**
     * Converts this SubscribeToRatePlan into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SubscribeToRatePlan [" + "productRatePlanId=" + productRatePlanId
                + ", subscribeToRatePlansChargeOverrides=" + subscribeToRatePlansChargeOverrides
                + "]";
    }

    /**
     * Builds a new {@link SubscribeToRatePlan.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SubscribeToRatePlan.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .productRatePlanId(getProductRatePlanId())
                .subscribeToRatePlansChargeOverrides(getSubscribeToRatePlansChargeOverrides());
        return builder;
    }

    /**
     * Class to build instances of {@link SubscribeToRatePlan}.
     */
    public static class Builder {
        private String productRatePlanId;
        private List<SubscribeToRatePlansChargeOverride> subscribeToRatePlansChargeOverrides;



        /**
         * Setter for productRatePlanId.
         * @param  productRatePlanId  String value for productRatePlanId.
         * @return Builder
         */
        public Builder productRatePlanId(String productRatePlanId) {
            this.productRatePlanId = productRatePlanId;
            return this;
        }

        /**
         * Setter for subscribeToRatePlansChargeOverrides.
         * @param  subscribeToRatePlansChargeOverrides  List of SubscribeToRatePlansChargeOverride
         *         value for subscribeToRatePlansChargeOverrides.
         * @return Builder
         */
        public Builder subscribeToRatePlansChargeOverrides(
                List<SubscribeToRatePlansChargeOverride> subscribeToRatePlansChargeOverrides) {
            this.subscribeToRatePlansChargeOverrides = subscribeToRatePlansChargeOverrides;
            return this;
        }

        /**
         * Builds a new {@link SubscribeToRatePlan} object using the set fields.
         * @return {@link SubscribeToRatePlan}
         */
        public SubscribeToRatePlan build() {
            return new SubscribeToRatePlan(productRatePlanId, subscribeToRatePlansChargeOverrides);
        }
    }
}
