/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TermsAndConditions type.
 */
public class TermsAndConditions {
    private Boolean autorenew;

    /**
     * Default constructor.
     */
    public TermsAndConditions() {
    }

    /**
     * Initialization constructor.
     * @param  autorenew  Boolean value for autorenew.
     */
    public TermsAndConditions(
            Boolean autorenew) {
        this.autorenew = autorenew;
    }

    /**
     * Getter for Autorenew.
     * autorenew flag
     * @return Returns the Boolean
     */
    @JsonGetter("autorenew")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getAutorenew() {
        return autorenew;
    }

    /**
     * Setter for Autorenew.
     * autorenew flag
     * @param autorenew Value for Boolean
     */
    @JsonSetter("autorenew")
    public void setAutorenew(Boolean autorenew) {
        this.autorenew = autorenew;
    }

    /**
     * Converts this TermsAndConditions into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TermsAndConditions [" + "autorenew=" + autorenew + "]";
    }

    /**
     * Builds a new {@link TermsAndConditions.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TermsAndConditions.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .autorenew(getAutorenew());
        return builder;
    }

    /**
     * Class to build instances of {@link TermsAndConditions}.
     */
    public static class Builder {
        private Boolean autorenew;



        /**
         * Setter for autorenew.
         * @param  autorenew  Boolean value for autorenew.
         * @return Builder
         */
        public Builder autorenew(Boolean autorenew) {
            this.autorenew = autorenew;
            return this;
        }

        /**
         * Builds a new {@link TermsAndConditions} object using the set fields.
         * @return {@link TermsAndConditions}
         */
        public TermsAndConditions build() {
            return new TermsAndConditions(autorenew);
        }
    }
}
