/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for TriggerDate type.
 */
public class TriggerDate {
    private String name;
    private String triggerDate;

    /**
     * Default constructor.
     */
    public TriggerDate() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  triggerDate  String value for triggerDate.
     */
    public TriggerDate(
            String name,
            String triggerDate) {
        this.name = name;
        this.triggerDate = triggerDate;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for TriggerDate.
     * Date in YYYY-MM-DD format.
     * @return Returns the String
     */
    @JsonGetter("triggerDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTriggerDate() {
        return triggerDate;
    }

    /**
     * Setter for TriggerDate.
     * Date in YYYY-MM-DD format.
     * @param triggerDate Value for String
     */
    @JsonSetter("triggerDate")
    public void setTriggerDate(String triggerDate) {
        this.triggerDate = triggerDate;
    }

    /**
     * Converts this TriggerDate into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TriggerDate [" + "name=" + name + ", triggerDate=" + triggerDate + "]";
    }

    /**
     * Builds a new {@link TriggerDate.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TriggerDate.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .name(getName())
                .triggerDate(getTriggerDate());
        return builder;
    }

    /**
     * Class to build instances of {@link TriggerDate}.
     */
    public static class Builder {
        private String name;
        private String triggerDate;



        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for triggerDate.
         * @param  triggerDate  String value for triggerDate.
         * @return Builder
         */
        public Builder triggerDate(String triggerDate) {
            this.triggerDate = triggerDate;
            return this;
        }

        /**
         * Builds a new {@link TriggerDate} object using the set fields.
         * @return {@link TriggerDate}
         */
        public TriggerDate build() {
            return new TriggerDate(name, triggerDate);
        }
    }
}
