/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for UpdateSubscriptionProcessingOptions type.
 */
public class UpdateSubscriptionProcessingOptions {
    private Boolean runBilling;
    private Boolean collectPayment;

    /**
     * Default constructor.
     */
    public UpdateSubscriptionProcessingOptions() {
    }

    /**
     * Initialization constructor.
     * @param  runBilling  Boolean value for runBilling.
     * @param  collectPayment  Boolean value for collectPayment.
     */
    public UpdateSubscriptionProcessingOptions(
            Boolean runBilling,
            Boolean collectPayment) {
        this.runBilling = runBilling;
        this.collectPayment = collectPayment;
    }

    /**
     * Getter for RunBilling.
     * Indicates if the current request needs to generate an invoice. The invoice will be generated
     * against all subscriptions included in this order.
     * @return Returns the Boolean
     */
    @JsonGetter("runBilling")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getRunBilling() {
        return runBilling;
    }

    /**
     * Setter for RunBilling.
     * Indicates if the current request needs to generate an invoice. The invoice will be generated
     * against all subscriptions included in this order.
     * @param runBilling Value for Boolean
     */
    @JsonSetter("runBilling")
    public void setRunBilling(Boolean runBilling) {
        this.runBilling = runBilling;
    }

    /**
     * Getter for CollectPayment.
     * Indicates if the current request needs to collect payments. This value can not be 'true' when
     * 'runBilling' flag is 'false'.
     * @return Returns the Boolean
     */
    @JsonGetter("collectPayment")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCollectPayment() {
        return collectPayment;
    }

    /**
     * Setter for CollectPayment.
     * Indicates if the current request needs to collect payments. This value can not be 'true' when
     * 'runBilling' flag is 'false'.
     * @param collectPayment Value for Boolean
     */
    @JsonSetter("collectPayment")
    public void setCollectPayment(Boolean collectPayment) {
        this.collectPayment = collectPayment;
    }

    /**
     * Converts this UpdateSubscriptionProcessingOptions into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateSubscriptionProcessingOptions [" + "runBilling=" + runBilling
                + ", collectPayment=" + collectPayment + "]";
    }

    /**
     * Builds a new {@link UpdateSubscriptionProcessingOptions.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateSubscriptionProcessingOptions.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .runBilling(getRunBilling())
                .collectPayment(getCollectPayment());
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateSubscriptionProcessingOptions}.
     */
    public static class Builder {
        private Boolean runBilling;
        private Boolean collectPayment;



        /**
         * Setter for runBilling.
         * @param  runBilling  Boolean value for runBilling.
         * @return Builder
         */
        public Builder runBilling(Boolean runBilling) {
            this.runBilling = runBilling;
            return this;
        }

        /**
         * Setter for collectPayment.
         * @param  collectPayment  Boolean value for collectPayment.
         * @return Builder
         */
        public Builder collectPayment(Boolean collectPayment) {
            this.collectPayment = collectPayment;
            return this;
        }

        /**
         * Builds a new {@link UpdateSubscriptionProcessingOptions} object using the set fields.
         * @return {@link UpdateSubscriptionProcessingOptions}
         */
        public UpdateSubscriptionProcessingOptions build() {
            return new UpdateSubscriptionProcessingOptions(runBilling, collectPayment);
        }
    }
}
