/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for UpdateSubscriptionSubscription type.
 */
public class UpdateSubscriptionSubscription {
    private String subscriptionNumber;
    private List<UpdateOrderOrderAction> orderActions;

    /**
     * Default constructor.
     */
    public UpdateSubscriptionSubscription() {
    }

    /**
     * Initialization constructor.
     * @param  subscriptionNumber  String value for subscriptionNumber.
     * @param  orderActions  List of UpdateOrderOrderAction value for orderActions.
     */
    public UpdateSubscriptionSubscription(
            String subscriptionNumber,
            List<UpdateOrderOrderAction> orderActions) {
        this.subscriptionNumber = subscriptionNumber;
        this.orderActions = orderActions;
    }

    /**
     * Getter for SubscriptionNumber.
     * Subscription number or ID. Subscription status must be active for the same.
     * @return Returns the String
     */
    @JsonGetter("subscriptionNumber")
    public String getSubscriptionNumber() {
        return subscriptionNumber;
    }

    /**
     * Setter for SubscriptionNumber.
     * Subscription number or ID. Subscription status must be active for the same.
     * @param subscriptionNumber Value for String
     */
    @JsonSetter("subscriptionNumber")
    public void setSubscriptionNumber(String subscriptionNumber) {
        this.subscriptionNumber = subscriptionNumber;
    }

    /**
     * Getter for OrderActions.
     * The actions to be applied to the subscription. Order actions will be stored with the sequence
     * when it was provided in the request.
     * @return Returns the List of UpdateOrderOrderAction
     */
    @JsonGetter("orderActions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<UpdateOrderOrderAction> getOrderActions() {
        return orderActions;
    }

    /**
     * Setter for OrderActions.
     * The actions to be applied to the subscription. Order actions will be stored with the sequence
     * when it was provided in the request.
     * @param orderActions Value for List of UpdateOrderOrderAction
     */
    @JsonSetter("orderActions")
    public void setOrderActions(List<UpdateOrderOrderAction> orderActions) {
        this.orderActions = orderActions;
    }

    /**
     * Converts this UpdateSubscriptionSubscription into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UpdateSubscriptionSubscription [" + "subscriptionNumber=" + subscriptionNumber
                + ", orderActions=" + orderActions + "]";
    }

    /**
     * Builds a new {@link UpdateSubscriptionSubscription.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UpdateSubscriptionSubscription.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(subscriptionNumber)
                .orderActions(getOrderActions());
        return builder;
    }

    /**
     * Class to build instances of {@link UpdateSubscriptionSubscription}.
     */
    public static class Builder {
        private String subscriptionNumber;
        private List<UpdateOrderOrderAction> orderActions;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  subscriptionNumber  String value for subscriptionNumber.
         */
        public Builder(String subscriptionNumber) {
            this.subscriptionNumber = subscriptionNumber;
        }

        /**
         * Setter for subscriptionNumber.
         * @param  subscriptionNumber  String value for subscriptionNumber.
         * @return Builder
         */
        public Builder subscriptionNumber(String subscriptionNumber) {
            this.subscriptionNumber = subscriptionNumber;
            return this;
        }

        /**
         * Setter for orderActions.
         * @param  orderActions  List of UpdateOrderOrderAction value for orderActions.
         * @return Builder
         */
        public Builder orderActions(List<UpdateOrderOrderAction> orderActions) {
            this.orderActions = orderActions;
            return this;
        }

        /**
         * Builds a new {@link UpdateSubscriptionSubscription} object using the set fields.
         * @return {@link UpdateSubscriptionSubscription}
         */
        public UpdateSubscriptionSubscription build() {
            return new UpdateSubscriptionSubscription(subscriptionNumber, orderActions);
        }
    }
}
