/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.exceptions;

import com.example.www.models.InvalidReqTypeError;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for InvalidReqTypeException type.
 */
public class InvalidReqTypeException extends ApiException {
    private static final long serialVersionUID = -40518327080946443L;
    private InvalidReqTypeError invalidReqTypeError;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public InvalidReqTypeException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for InvalidReqTypeError.
     * @return Returns the InvalidReqTypeError
     */
    @JsonGetter("InvalidReqTypeError")
    public InvalidReqTypeError getInvalidReqTypeError() {
        return this.invalidReqTypeError;
    }

    /**
     * Setter for InvalidReqTypeError.
     * @param invalidReqTypeError Value for InvalidReqTypeError
     */
    @JsonSetter("InvalidReqTypeError")
    private void setInvalidReqTypeError(InvalidReqTypeError invalidReqTypeError) {
        this.invalidReqTypeError = invalidReqTypeError;
    }

    /**
     * Converts this InvalidReqTypeException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InvalidReqTypeException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", invalidReqTypeError=" + invalidReqTypeError + "]";
    }
}
