/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.example.www.exceptions;

import com.example.www.models.OrderRespError;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for OrderRespTypeErrorException type.
 */
public class OrderRespTypeErrorException extends ApiException {
    private static final long serialVersionUID = -1107554120243112897L;
    private String orderNumber;
    private String subscriptionId;
    private OrderRespError orderRespError;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public OrderRespTypeErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for OrderNumber.
     * Order Number.
     * @return Returns the String
     */
    @JsonGetter("orderNumber")
    public String getOrderNumber() {
        return this.orderNumber;
    }

    /**
     * Setter for OrderNumber.
     * Order Number.
     * @param orderNumber Value for String
     */
    @JsonSetter("orderNumber")
    private void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * Getter for SubscriptionId.
     * Pearson subscription id.
     * @return Returns the String
     */
    @JsonGetter("subscriptionId")
    public String getSubscriptionId() {
        return this.subscriptionId;
    }

    /**
     * Setter for SubscriptionId.
     * Pearson subscription id.
     * @param subscriptionId Value for String
     */
    @JsonSetter("subscriptionId")
    private void setSubscriptionId(String subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    /**
     * Getter for OrderRespError.
     * @return Returns the OrderRespError
     */
    @JsonGetter("orderRespError")
    public OrderRespError getOrderRespError() {
        return this.orderRespError;
    }

    /**
     * Setter for OrderRespError.
     * @param orderRespError Value for OrderRespError
     */
    @JsonSetter("orderRespError")
    private void setOrderRespError(OrderRespError orderRespError) {
        this.orderRespError = orderRespError;
    }

    /**
     * Converts this OrderRespTypeErrorException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OrderRespTypeErrorException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", orderNumber=" + orderNumber + ", subscriptionId="
                + subscriptionId + ", orderRespError=" + orderRespError + "]";
    }
}
